OPENWEATHER_API_ENDPOINT = "https://api.openweathermap.org/data/2.5"
CURRENT_AIR_POLLUTION_ENDPOINT = f"{OPENWEATHER_API_ENDPOINT}/air_pollution"
HISTORY_AIR_POLLUTION_ENDPOINT = f"{OPENWEATHER_API_ENDPOINT}/air_pollution/history"
