france_air_pollution:  # Must match "profile" in dbt_project.yml
  outputs:
    dev:
      dataset: development
      job_execution_timeout_seconds: 300
      job_retries: 3
      keyfile: /usr/local/airflow/include/keys/gcp-key.json
      location: europe-west2
      method: service-account
      priority: interactive
      project: paris-air-pollution-quangnc
      threads: 4
      type: bigquery

    prod:
      dataset: production
      job_execution_timeout_seconds: 300
      job_retries: 3
      keyfile: /usr/local/airflow/include/keys/gcp-key.json
      location: europe-west2
      method: service-account
      priority: interactive
      project: paris-air-pollution-quangnc
      threads: 4
      type: bigquery

  target: dev